### PR TITLE
Add dynamic page titles

### PR DESCRIPTION
**Pull request by SchoolyB**
Page titles in the browser tabs now say "StratGG / [Name of page]". A simple but good change.

### CODE REVIEW

**Comment by Inter3sted** [comment]
If someone were to have multiple tabs open, would that start getting crowded on their browser?

**Comment by SchoolyB** [comment]
> If someone were to have multiple tabs open, would that start getting crowded on their browser?

To answer that question I dont think so. I think it will actually help keep it organized as opposed to having multiple tabs that just say "StratGG".


Screenshot_8

**Review by Inter3sted — APPROVED** [review]
What if there are subdirectories of those pages in the future? Will we need a new convention for that? StratGG/Home/Tourniquet/Image.png

**Comment by SchoolyB** [comment]
Nothing of that length at best one more word being the `/` and even then that'd be done most likely for player pages....

"StratGG/Player Bio/ Player 1245"

**Pull request merged**
